/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_SC_Wrapper */

#ifndef _Included_jni_SC_Wrapper
#define _Included_jni_SC_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_SC_Wrapper
 * Method:    frame2feature
 * Signature: ([SI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jni_SC_1Wrapper_frame2feature
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     jni_SC_Wrapper
 * Method:    frameDistance
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_SC_1Wrapper_frameDistance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     jni_SC_Wrapper
 * Method:    wav2splice
 * Signature: (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;ZIIDDIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_SC_1Wrapper_wav2splice
  (JNIEnv *, jobject, jobject, jstring, jstring, jboolean, jint, jint, jdouble, jdouble, jint, jint, jint, jint);

/*
 * Class:     jni_SC_Wrapper
 * Method:    wav2features
 * Signature: (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;IIZZIIDIIIIDDDIIIDDDDDDDDDDID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_SC_1Wrapper_wav2features
  (JNIEnv *, jobject, jobject, jstring, jstring, jint, jint, jboolean, jboolean, jint, jint, jdouble, jint, jint, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdouble);

/*
 * Class:     jni_SC_Wrapper
 * Method:    wav2gmm
 * Signature: (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;IZDIDIIZZIIDIIIIDDDIIIDDDDDDDDDDID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_SC_1Wrapper_wav2gmm
  (JNIEnv *, jobject, jobject, jstring, jstring, jint, jboolean, jdouble, jint, jdouble, jint, jint, jboolean, jboolean, jint, jint, jdouble, jint, jint, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdouble);

/*
 * Class:     jni_SC_Wrapper
 * Method:    wav2hmm
 * Signature: (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;IIIILjava/lang/String;ZIIIZZIIDIIIIDDDIIIDDDDDDDDDDID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_SC_1Wrapper_wav2hmm
  (JNIEnv *, jobject, jobject, jstring, jstring, jint, jint, jint, jint, jstring, jboolean, jint, jint, jint, jboolean, jboolean, jint, jint, jdouble, jint, jint, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
